'use client';

import { useState } from 'react';
import Link from 'next/link';
import { 
  Cpu, 
  Sparkles, 
  Eye, 
  Target, 
  HelpCircle, 
  Layers, 
  ArrowRight, 
  CheckCircle2, 
  AlertTriangle,
  Zap,
  BarChart3,
  ShieldCheck,
  FileCheck2,
  FileCode,
  Lock,
  Code
} from 'lucide-react';
import ScrollReveal from '@/components/ScrollReveal';

export default function FeaturesPage() {
  const [selectedCategory, setSelectedCategory] = useState('all');

  const features = [
    {
      id: 'ats-sim',
      category: 'parsing',
      icon: <Cpu size={24} />,
      title: 'Multi-Engine ATS Abstract Syntax Tree Emulation',
      subtitle: 'Engineered for Workday, Greenhouse, Taleo & iCIMS',
      description: 'Legacy resume checkers test against generic keyword counters. ResumeIQ simulates the parsing Abstract Syntax Tree (AST) and linear coordinate stream generated by enterprise ATS platforms, flagging multi-column interleaving, floating text box stripping, and header margin contact occlusion.',
      specs: [
        'Multi-column layout horizontal collision detection (Workday linear scan)',
        'Canonical section heading standardization (Greenhouse taxonomy)',
        'Vector graphic & custom symbol substitution sanitizer (Taleo)',
        'Header/footer margin contact occlusion bounds checking (iCIMS)'
      ]
    },
    {
      id: 'verb-quantifier',
      category: 'linguistics',
      icon: <Target size={24} />,
      title: 'Syntactic Action-Verb & Metric Extraction',
      subtitle: 'Part-of-Speech Tagging & Quantitative Validation',
      description: 'Human recruiters reject resumes filled with passive task descriptions (e.g., "Responsible for bug fixes"). Our linguistic engine analyzes sentence grammar, classifies verbs into Strong/Moderate/Weak tiers, and verifies whether claims are backed by quantifiable proof (%, $, multipliers, volume scale).',
      specs: [
        'Grammatical part-of-speech leading verb extraction',
        'Regex syntactic extraction of percentages, dollar values, multipliers (3x), and user volume (2M MAU)',
        'Quantified Bullet Ratio calculation (Target: ≥70% quantified bullets)',
        'Real-time weak verb highlight and replacement recommendations'
      ]
    },
    {
      id: 'gaze-replay',
      category: 'heuristics',
      icon: <Eye size={24} />,
      title: '6-Second Recruiter Attention Heatmap',
      subtitle: 'Cognitive F-Pattern Visual Scan Modeling',
      description: 'Eye-tracking studies of professional technical recruiters demonstrate that initial screening decisions occur within 6 to 7.4 seconds following an F-pattern scan. ResumeIQ models visual dwell time across document zones to verify high-impact achievements sit in the top 35% fold.',
      specs: [
        'Cognitive dwell-time distribution modeling (Header 95%, Summary 85%, Bullets 50%, Lower 25%)',
        'Above-the-fold content impact density calculation',
        'Section visual balance and typographical hierarchy analysis',
        'Interactive step-by-step dwell time replay'
      ]
    },
    {
      id: 'jd-matcher',
      category: 'parsing',
      icon: <Layers size={24} />,
      title: 'Boundary-Aware Keyword & Alias Matcher',
      subtitle: 'Zero False-Positives with Technical Synonym Graph',
      description: 'Traditional resume checkers use naive substring searching that incorrectly matches words like "Java" inside "JavaScript" or "Go" in "Good". ResumeIQ uses strict word boundaries and an extensive technical alias graph to map synonyms like K8s to Kubernetes and Postgres to PostgreSQL.',
      specs: [
        'Strict regex boundary matching (\\b[Skill]\\b) eliminating substring false positives',
        'Technical alias graph matching synonyms (GCP → Google Cloud, TS → TypeScript)',
        'Categorized Hard Skills, Soft Skills, and Domain Tool classification',
        'Target Job Description gap analysis with missing critical skill lists'
      ]
    },
    {
      id: 'star-rewriter',
      category: 'coaching',
      icon: <Sparkles size={24} />,
      title: 'Grounded STAR Bullet Rewriter',
      subtitle: 'Selective LLM Reasoning with PII Redaction',
      description: 'Transforms vague statements into quantified Situation-Task-Action-Result achievements. Prompts are dispatched to high-throughput Groq LLaMA 3.3 70B models only after candidate PII has been scrubbed and tokenized in-flight.',
      specs: [
        'Transforms passive duties into active business outcomes with metrics',
        'Maintains candidate truthfulness by generating metric placeholders [X%] for unquantified claims',
        'Three distinct style variations: Metric-Dense, Architectural, and Executive',
        'In-flight PII redaction ensures no personal identity data leaves the server'
      ]
    },
    {
      id: 'interview-prep',
      category: 'coaching',
      icon: <HelpCircle size={24} />,
      title: 'Predictive Technical & Behavioral Interview Engine',
      subtitle: 'Resume-Grounded Question Prediction',
      description: 'Analyzes specific architectural claims, tools, and leadership responsibilities listed on your resume to anticipate the exact behavioral, technical, and system design questions an engineering manager or screener will ask during interviews.',
      specs: [
        'System design and deep architecture probes mapped to specific tools listed',
        'Behavioral questions targeting conflict resolution and deadline pressure claims',
        'Interviewer talking points and recommended STAR answer frameworks',
        'Vulnerability and claim-gap detection'
      ]
    },
    {
      id: 'privacy-first',
      category: 'heuristics',
      icon: <Lock size={24} />,
      title: 'Zero-Retention Privacy & Local Offline Sandbox',
      subtitle: 'Air-Gapped Execution Capability',
      description: 'Your career data belongs strictly to you. ResumeIQ operates with zero central data retention for unauthenticated scans, ephemerally unlinks uploaded files, and includes an embedded zero-dependency datastore fallback allowing full local execution.',
      specs: [
        'Ephemeral memory processing with automated file unlink',
        'PostgreSQL + pgvector with local zero-config JSON datastore fallback',
        'Client and server-side in-flight PII tokenization',
        '100% offline air-gapped capability for core heuristic engine'
      ]
    }
  ];

  const filteredFeatures = selectedCategory === 'all' 
    ? features 
    : features.filter(f => f.category === selectedCategory);

  return (
    <div style={{ paddingTop: 100, paddingBottom: 80, maxWidth: 1140, margin: '0 auto', paddingLeft: 20, paddingRight: 20 }}>
      {/* ─── Hero Section ─── */}
      <section style={{ textAlign: 'center', paddingTop: 20, paddingBottom: 40 }}>
        <ScrollReveal>
          <div className="badge badge-blue" style={{ marginBottom: 16 }}>
            <Cpu size={13} /> Technical Specifications
          </div>
          <h1 style={{ fontSize: 'clamp(2.2rem, 4vw, 3.2rem)', marginBottom: 16 }}>
            Engineered Subsystems & Architecture
          </h1>
          <p style={{ color: 'var(--text-secondary)', maxWidth: 680, margin: '0 auto 32px', fontSize: '1.05rem', lineHeight: 1.6 }}>
            A comprehensive breakdown of the parsing algorithms, grammatical classifiers, ATS AST emulators, and privacy safeguards powering ResumeIQ.
          </p>

          {/* Category Filter Pills */}
          <div className="segmented-nav" style={{ maxWidth: 540, margin: '0 auto' }}>
            <button
              className={`segmented-item ${selectedCategory === 'all' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('all')}
            >
              All Subsystems ({features.length})
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'parsing' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('parsing')}
            >
              ATS & Parsing
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'linguistics' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('linguistics')}
            >
              Linguistics
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'heuristics' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('heuristics')}
            >
              Heuristics
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'coaching' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('coaching')}
            >
              AI Coaching
            </button>
          </div>
        </ScrollReveal>
      </section>

      {/* ─── Features Grid ─── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: 24, marginTop: 32 }}>
        {filteredFeatures.map((feat) => (
          <article 
            key={feat.id}
            style={{ 
              background: 'var(--bg-app)', 
              border: '1px solid var(--border)', 
              borderRadius: 'var(--r-lg)', 
              padding: 28,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              boxShadow: 'var(--shadow-xs)'
            }}
          >
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14 }}>
                <div style={{ color: 'var(--accent)', padding: 8, background: 'var(--accent-muted)', borderRadius: 'var(--r-md)' }}>
                  {feat.icon}
                </div>
                <div>
                  <h3 style={{ fontSize: '1.15rem', marginBottom: 2 }}>{feat.title}</h3>
                  <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>{feat.subtitle}</span>
                </div>
              </div>

              <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem', lineHeight: 1.65, marginBottom: 20 }}>
                {feat.description}
              </p>

              <div style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: 16, marginBottom: 16 }}>
                <strong style={{ fontSize: '0.78rem', textTransform: 'uppercase', letterSpacing: '0.04em', color: 'var(--text-muted)' }}>
                  Key Engineering Specs:
                </strong>
                <ul style={{ listStyle: 'none', padding: 0, marginTop: 8 }}>
                  {feat.specs.map((spec, i) => (
                    <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: 8, lineHeight: 1.5 }}>
                      <CheckCircle2 size={14} style={{ color: 'var(--success)', flexShrink: 0, marginTop: 3 }} />
                      <span>{spec}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div style={{ paddingTop: 8 }}>
              <span className="badge badge-neutral" style={{ textTransform: 'capitalize' }}>
                Subsystem: {feat.category}
              </span>
            </div>
          </article>
        ))}
      </div>

      {/* ─── Bottom CTA ─── */}
      <section style={{ marginTop: 64, padding: '40px 32px', background: 'var(--bg-app)', border: '1px solid var(--border)', borderRadius: 'var(--r-lg)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 20 }}>
        <div>
          <h2 style={{ fontSize: '1.5rem', marginBottom: 4 }}>Ready to analyze your resume?</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Experience instant deterministic scoring backed by deep AST heuristics.</p>
        </div>
        <Link href="/auth" className="btn btn-primary btn-lg">
          Launch Workspace <ArrowRight size={15} />
        </Link>
      </section>
    </div>
  );
}
