'use client';

import { useState } from 'react';
import Link from 'next/link';
import { 
  Cpu, 
  Sparkles, 
  Eye, 
  Target, 
  HelpCircle, 
  Layers, 
  ArrowRight, 
  CheckCircle2, 
  AlertTriangle,
  Zap,
  BarChart3,
  ShieldCheck,
  FileCheck2,
  FileCode
} from 'lucide-react';
import ScrollReveal from '@/components/ScrollReveal';

export default function FeaturesPage() {
  const [selectedCategory, setSelectedCategory] = useState('all');

  const features = [
    {
      id: 'ats-sim',
      category: 'parsing',
      icon: <Cpu size={24} />,
      title: 'Multi-Engine ATS Parser Simulation',
      subtitle: 'Engineered for Workday, Greenhouse, Taleo & Lever',
      description: 'Legacy ATS checkers test against arbitrary keyword rules. ResumeIQ simulates the exact parsing AST (Abstract Syntax Tree) generated by major corporate hiring platforms, flagging unparseable columns, problematic text boxes, non-standard symbols, and header collision errors.',
      points: [
        'Multi-column layout collision warnings',
        'Section heading semantic standardization',
        'Non-standard bullet character sanitization',
        'Date format normalization (MM/YYYY vs. String dates)'
      ]
    },
    {
      id: 'star-rewriter',
      category: 'ai',
      icon: <Sparkles size={24} />,
      title: 'STAR Metric Bullet Point Quantifier',
      subtitle: 'Situation • Task • Action • Result',
      description: 'Recruiters reject resumes with passive task descriptions (e.g., "Responsible for customer support"). Our AI agent parses each bullet, identifies missing metrics, and drafts impactful STAR rewrites showing scale, velocity, and business outcome.',
      points: [
        'Automatic weak verb and passive voice detection',
        'Inference of implied metrics based on role seniority',
        'Three alternate rewrite variations (Concise, Metrics-Heavy, Executive)',
        '1-click replacement preview'
      ]
    },
    {
      id: 'gaze-replay',
      category: 'analytics',
      icon: <Eye size={24} />,
      title: '6-Second Recruiter Dwell Time Replay',
      subtitle: 'Eye-Tracking & Attention Modeling',
      description: 'Recruiters spend an average of 6 to 7.4 seconds on an initial resume screen. ResumeIQ calculates visual dwell time, simulating the classic F-pattern scan to verify that your highest-impact credentials appear in the top 35% of the visual fold.',
      points: [
        'Visual heat map distribution',
        'Above-the-fold content optimization score',
        'Skill visibility density index',
        'Actionable positioning adjustments'
      ]
    },
    {
      id: 'interview-prep',
      category: 'ai',
      icon: <HelpCircle size={24} />,
      title: 'AI Interview Question Predictor',
      subtitle: 'Technical & Behavioral Probe Simulation',
      description: 'Using LLaMA 3.3 70B parameter models, ResumeIQ generates the exact technical probe questions and behavioral situational questions hiring managers and engineering leads will ask based on the specific claims in your resume.',
      points: [
        'System design questions for engineering claims',
        'Behavioral questions targeting leadership & conflict claims',
        'Model answers with recommended STAR frameworks',
        'Gaps and vulnerability analysis'
      ]
    },
    {
      id: 'jd-matcher',
      category: 'parsing',
      icon: <Target size={24} />,
      title: 'Semantic Job Description Alignment',
      subtitle: 'Vectorized Similarity & Missing Skill Matrix',
      description: 'Compare your resume against any job description. ResumeIQ extracts required core competencies, distinguishes mandatory vs. nice-to-have qualifications, and highlights exactly which skills you need to add to reach top-tier match tiers.',
      points: [
        'Hard skills & software proficiency gap analysis',
        'Soft skills & leadership competency alignment',
        'Keyword density recommendation without keyword stuffing',
        'Role-tailored resume draft generator'
      ]
    },
    {
      id: 'privacy-first',
      category: 'analytics',
      icon: <ShieldCheck size={24} />,
      title: 'Zero-Retention Privacy Architecture',
      subtitle: 'Confidential • Local Fallback • Secure Sandbox',
      description: 'Your career data belongs strictly to you. ResumeIQ runs transparently with full export and one-click document deletion controls. No uploaded resumes are ever sold, shared, or used to train closed commercial models.',
      points: [
        'Zero-retention private processing sandbox',
        'Docker containerized deployment with one command',
        'Dual-mode PostgreSQL with local zero-config JSON fallback',
        'Full document and history deletion on demand'
      ]
    }
  ];

  const filteredFeatures = selectedCategory === 'all' 
    ? features 
    : features.filter(f => f.category === selectedCategory);

  return (
    <div style={{ paddingTop: 100, paddingBottom: 80 }}>
      {/* ─── Hero Section ─── */}
      <section className="section" style={{ textAlign: 'center', paddingTop: 20, paddingBottom: 40 }}>
        <ScrollReveal>
          <span className="section-label">Architecture & Features</span>
          <h1 style={{ fontSize: 'clamp(2.2rem, 4vw, 3.2rem)', marginBottom: 16 }}>
            Comprehensive <span className="gradient-text">Resume Intelligence</span> Engine
          </h1>
          <p style={{ color: 'var(--text-secondary)', maxWidth: 640, margin: '0 auto 32px', fontSize: '1.1rem' }}>
            Explore the complete suite of parsing algorithms, semantic AI agents, and diagnostic tools built into ResumeIQ.
          </p>

          {/* Category Filter Pills */}
          <div className="segmented-nav" style={{ maxWidth: 440, margin: '0 auto' }}>
            <button
              className={`segmented-item ${selectedCategory === 'all' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('all')}
            >
              All Features (6)
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'parsing' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('parsing')}
            >
              ATS & Parsing
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'ai' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('ai')}
            >
              AI Agents
            </button>
            <button
              className={`segmented-item ${selectedCategory === 'analytics' ? 'active' : ''}`}
              onClick={() => setSelectedCategory('analytics')}
            >
              Analytics
            </button>
          </div>
        </ScrollReveal>
      </section>

      {/* ─── Features Grid ─── */}
      <section className="section" style={{ paddingTop: 0 }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
          {filteredFeatures.map((feat, idx) => (
            <ScrollReveal key={feat.id}>
              <div className="card tilt-card" style={{ padding: '36px 32px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 24, alignItems: 'start' }}>
                  <div className="feature-icon-wrapper" style={{ width: 56, height: 56, marginTop: 4 }}>
                    {feat.icon}
                  </div>

                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4, flexWrap: 'wrap' }}>
                      <h2 style={{ fontSize: '1.4rem', fontWeight: 800 }}>{feat.title}</h2>
                      <span className="badge badge-primary">{feat.subtitle}</span>
                    </div>

                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.7, marginBottom: 20 }}>
                      {feat.description}
                    </p>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 10 }}>
                      {feat.points.map((pt, i) => (
                        <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: '0.85rem' }}>
                          <CheckCircle2 size={16} style={{ color: 'var(--success)', flexShrink: 0, marginTop: 3 }} />
                          <span style={{ color: 'var(--text-primary)', fontWeight: 500 }}>{pt}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </section>

      {/* ─── Bottom CTA ─── */}
      <section className="cta-section" style={{ paddingTop: 20 }}>
        <ScrollReveal>
          <div className="cta-card">
            <h2 style={{ fontSize: '1.8rem', marginBottom: 12 }}>Ready to Test These Features on Your Resume?</h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: 24 }}>
              Zero subscription required. Upload your document and receive complete diagnostic reports instantly.
            </p>
            <Link href="/auth" className="btn btn-primary btn-lg">
              Start Free Audit <ArrowRight size={15} />
            </Link>
          </div>
        </ScrollReveal>
      </section>
    </div>
  );
}
